### ISSUE TITLE
Display current date & time on Landing page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#15]
**User Story Description**
As an end user 
I want to see the current date & time displayed on the screen 
So I can easily reference it

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by thiagorasouza** [comment]
As I forgot to reference this issue, here goes the link for the last datetime commit
[https://github.com/chingu-voyages/v23-toucans-team-02/commit/f9123a16647a0db77a08ae7326db2b0b6d808a51](https://github.com/chingu-voyages/v23-toucans-team-02/commit/f9123a16647a0db77a08ae7326db2b0b6d808a51)
