### ISSUE TITLE
Display current temperature on Landing page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#16]
**User Story Description**
As an end user 
I want to see the current temperature in my preferred unit of measure (fahrenheit or celcius) displayed on the screen 
So I can easily reference it

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by OmarAlareeki** [comment]
Displaying current temperature on landing page, I think it is complete and this issue should be closed.
