### ISSUE TITLE
Display icon summarizing current weather condition on Landing page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#17]
**User Story Description**
As an end user 
I want to see the current weather conditions summarized as an icon on the screen 
So I can easily reference it

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by OmarAlareeki** [comment]
This should be closed today after meeting.
