### ISSUE TITLE
User must be able to choose temperature units

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#19]
**User Story Description**
As an end user 
I want do select the unit of measure for temperatures (celcius or fahrenheit)
So it reflects my regional standard

**Steps to Follow (optional)**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by tomrhudson** [comment]
FYI: In my weather.js file I have a variable that can obtain the user selection using a document.getElementID call. At the moment, the variable is hardcoded to imperial.
