### ISSUE TITLE
Persist the users selection of the temperature display unit

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#6]
**Feature Description**
The users selection of the temperature display unit to be used should persist across browser sessions

**Major User Stories**
- [ ] As an end user I want my selection of the temperature display unit to persist across browser sessions

**Additional Considerations**
[Using HTTP Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)

**Comment by tomrhudson** [comment]
in my current branch, I have it were the browser remembers your zipcode therefore we can use the same functionality for this feature 

@smellaphant - tagging you as you have Issue #19 which you could potentially pull this into scope once you have the temp selectors developed

**Comment by OmarAlareeki** [comment]
I have fixed this issue on my end in the weather.js file.
