### ISSUE TITLE
Allow user to change app style

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v23-toucans-team-02#9]
**Feature Description**
Allow the user to change the styling of the app including colors and font. This might be useful for someone with a vision impairment like color blindness.

**Major User Stories**
- [ ] As an end user I want to change the default app colors So I can select colors that better suits my preferences
- [ ] As an end user I want to change the default app font so I can select a font family that better suits my preferences

**Additional Considerations**
Question: What about dark/light mode?

**Comment by thiagorasouza** [comment]
On Question:
We could restrict this to light/dark theme in a first moment. If we have time then we could expand the scope.
